#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
memory_helper

Minimal global store for keeping:
- (vault_name -> password) pairs
- (session_id -> session_info) pairs

for the entire lifetime of the main process.

APIs:
- init_store()
- is_initialized()
- set(vault_name, password)
- get(vault_name)
- get_all()
- set_session(session_id, info_dict)
- get_session(session_id)
- delete_session(session_id)
- get_all_sessions()

Logs exclusively through log_helper.
"""

# Import project log helper
try:
    from UTIL import log_helper
except Exception:
    log_helper = None

# Global stores
_memory_store = {}     # vault_name -> password
_session_store = {}    # session_id -> { "ip":..., "port":..., "username":..., "password":..., "created":... }

# Initialization flag
_initialized = False


def _log(msg: str) -> None:
    """Write logs exclusively through log_helper."""
    try:
        if log_helper is not None:
            log_helper.info(msg)
        else:
            print(f"[memory_helper] {msg}")  # emergency fallback
    except Exception:
        pass


def init_store() -> None:
    """
    Initialize the global stores.
    Must be called once by main at startup.
    """
    global _memory_store, _session_store, _initialized
    _memory_store = {}
    _session_store = {}
    _initialized = True
    _log("memory_helper: stores initialized (empty dictionaries)")


def is_initialized() -> bool:
    """Return True if init_store() has been called."""
    return _initialized


# -------------------------
# Vault password API
# -------------------------
def set(vault_name: str, password: str) -> None:
    """
    Store or update the password associated with a vault.
    """
    global _memory_store
    _memory_store[vault_name] = password
    _log(f"memory_helper: stored password for vault '{vault_name}'")


def get(vault_name: str):
    """
    Retrieve the password associated with a vault, or None.
    """
    value = _memory_store.get(vault_name)
    _log(f"memory_helper: retrieved password for vault '{vault_name}' -> {value is not None}")
    return value


def get_all():
    """
    Return a copy of the entire vault store (debug only).
    """
    _log("memory_helper: full vault store dump requested")
    return dict(_memory_store)


# -------------------------
# Session store API
# -------------------------
def set_session(session_id: str, info: dict) -> None:
    """
    Store or update a session entry.

    session_id: unique string (e.g., session_number generated by SNS_connection)
    info: dict containing at least keys: ip, port, username, password, created (timestamp iso or epoch)
    """
    global _session_store
    try:
        _session_store[session_id] = dict(info)
        _log(f"memory_helper: stored session '{session_id}' -> ip={info.get('ip')} port={info.get('port')}")
    except Exception as e:
        _log(f"memory_helper: failed to store session '{session_id}': {e}")


def get_session(session_id: str):
    """
    Retrieve session info dict for session_id or None.
    """
    value = _session_store.get(session_id)
    _log(f"memory_helper: retrieved session '{session_id}' -> {value is not None}")
    return dict(value) if value is not None else None


def delete_session(session_id: str) -> bool:
    """
    Delete a session entry. Returns True if deleted, False if not found.
    """
    try:
        if session_id in _session_store:
            _session_store.pop(session_id, None)
            _log(f"memory_helper: deleted session '{session_id}'")
            return True
        else:
            _log(f"memory_helper: delete_session called for unknown session '{session_id}'")
            return False
    except Exception as e:
        _log(f"memory_helper: error deleting session '{session_id}': {e}")
        return False


def get_all_sessions():
    """
    Return a copy of the entire session store (debug only).
    """
    _log("memory_helper: full session store dump requested")
    return dict(_session_store)
